name: Kenna-SecretScanning-Action

on:
  schedule:
    - cron: "25 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:    
  
jobs:
   Kenna-Action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Toolkit Repo
      uses: actions/checkout@v2
      with:
        repository: KennaSecurity/toolkit
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2
    - name: Install dependencies
      run: bundle install --without development test
    - name: Debug
      run: |
        echo exec bundle exec ruby toolkit.rb task=github_secret_scanning github_token=${GH_TOKEN} kenna_connector_id=158098 github_username=${GH_USERNAME} kenna_api_host=api.sandbox.us.kennasecurity.com kenna_api_key=${KENNA_API_KEY} github_repositories=${GH_REPOS} | sed 's/./& /g'
      env:
        GH_TOKEN: "${{secrets.GH_TOKEN}}"
        GH_USERNAME: "${{secrets.GH_USERNAME}}"
        KENNA_API_KEY: "${{secrets.KENNA_API_KEY}}"
        GH_REPOS: "${{secrets.GH_REPOS}}"
        
    - name:  Run SCAN
      run : exec bundle exec ruby toolkit.rb task=github_secret_scanning github_token=${GH_TOKEN} kenna_connector_id=158098 github_username=${GH_USERNAME} kenna_api_host=api.sandbox.us.kennasecurity.com kenna_api_key=${KENNA_API_KEY} github_repositories=${GH_REPOS}
      env:
        GH_TOKEN: "${{secrets.GH_TOKEN}}"
        GH_USERNAME: "${{secrets.GH_USERNAME}}"
        KENNA_API_KEY: "${{secrets.KENNA_API_KEY}}"
        GH_REPOS: "${{secrets.GH_REPOS}}"
